import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import AppProvider from "@/context/appContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chating",
  description: "Generated by Talha",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <AppProvider>{children}</AppProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
